# Generated by Django 4.2.9 on 2024-02-03 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubrique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SousRubrique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "rubrique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulator.rubrique",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Devis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created on"),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        default=30, verbose_name="duree de devis (jours)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
            },
        ),
        migrations.CreateModel(
            name="ChargesFonctionnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prix_unitaire_mensuel", models.FloatField(default=0)),
                ("quantite", models.FloatField(default=0)),
                ("nombre_mois_annuel", models.FloatField(default=12)),
                (
                    "sous_rubrique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulator.sousrubrique",
                    ),
                ),
            ],
        ),
    ]
