# Generated by Django 4.2.9 on 2024-02-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_customuser_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="company",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
