# Generated by Django 4.2.9 on 2024-02-03 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("ACT", "En cours"), ("CLO", "Cloturé")],
                        default="ACT",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checked_out",
                    models.BooleanField(default=False, verbose_name="checked out"),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "cart",
                "verbose_name_plural": "cartsOf",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ItemRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_message", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity_instock", models.IntegerField(verbose_name="quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="unit price"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity_instock", models.IntegerField(verbose_name="quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="unit price"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.IntegerField(verbose_name="quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="unit price"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="cartcom.cartof",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "ItemArticle",
                "verbose_name_plural": "ItemArticles",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="cartof",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="carts", to="cartcom.itemarticle"
            ),
        ),
    ]
